### ISSUE TITLE
Absolutely Beginner instructions

### ISSUE THREAD

**Issue by kalvinMB** [LordKBX/wuxiaworld_export_ebook#1]
Hi,
I am one of the laymans who loves wuxiaworld as well. So in line with this,

Can you also please make an idiot/noob friendly instructions as well on how to use this. 
from downloading python until the finished ebook?
I am a mac user as well. :(

Thanks a lot mate..

**Comment by LordKBX** [comment]
Wait 1 week or 2 before i could give you an answer, i do not have personal Mac(honestly i do not like it), only one in my office so i note it in my to-do list but you may wait a long time

**Comment by kalvinMB** [comment]
Awesome. I can wait for as long as I can for this favor which is free. thanks alot

**Comment by LordKBX** [comment]
For Mac Users:
Install ANACONDA => https://www.anaconda.com/download/#macos
after installation open a terminal and use the command "conda install -c anaconda pyqt=4.11.4"
start the application with the start.sh(last update) or replace python with python3

**Comment by kalvinMB** [comment]
alright done..

**Comment by kalvinMB** [comment]
i have this problem: When I run the shell in idle.
"Traceback (most recent call last):
  File "/Users/KalMB/Downloads/wuxiaworld_export_ebook-master 2/wuxiaworld_export_ebook.pyw", line 9, in <module>
    from PyQt4 import QtCore, QtGui
ModuleNotFoundError: No module named 'PyQt4'"

please help

**Comment by kalvinMB** [comment]
Can you please convert this into a stand alone exe file? if it is hard then just forget it.

**Comment by kalvinMB** [comment]
Hi Mate, 
I think I was able to work it out now. Perfect.. Thanks a lot. A++ for you.
