### ISSUE TITLE
wuxiaworld.co?

### ISSUE THREAD

**Issue by kalvinMB** [LordKBX/wuxiaworld_export_ebook#3]
Hi LordKBX,

You did an awesome Job with wuxiaworld.com
you help us a lot both windows and mac users.

My questions is, would it be burdensome to tweak this code for wuxiaworld."co"? I noticed that this site has more novels to offer.

thanks.

**Comment by LordKBX** [comment]
wuxiaworld.co was a website that copy other website without the authorization of the original website nor crediting them nor paying them.
You also have the translator comments and lexical that where not separated from the chapters content, confusion readers

**Comment by kalvinMB** [comment]
Oh I see I understand.. Thanks still. Cheers
