### ISSUE TITLE
The script download the announcement rather than the novel

### ISSUE THREAD

**Issue by MrTazocin** [LordKBX/wuxiaworld_export_ebook#4]
Hi, can you please fix the script because it capture the wrong part which is the announcement.

Example:
https://www.wuxiaworld.com/novel/i-shall-seal-the-heavens/issth-book-1-chapter-1

It will capture this part only:
Wuxiaworld Welcomes Boko and 'Stop, Friendly Fire!'
Everyone, please join me in a warm Wuxiaworld welcome for our new Korean translator 'Boko' and his new project, 'Stop, Friendly Fire'!  SFF has been enjoyed by thousands of our VIP users on early access, and now we're opening it up to everyone!  It was previously known as 'Don't Shoot, I'm an Ally' and is a funny (and fun-to-read) LitRPG novel, where our main character gets pulled by a god of another world into a game-like world, with that god seeking a champion to carry out certain quests.  He asks for an 'immortal body'... and so that god (goddess, really) gives him the body of a friggin' skeleton (but one blessed by god!).  It's a riot to read, with him running around and posing as a skeleton amongst other skeleton mobs and then beating them up or talking them into helping him (to their deaths), then using their bones to reinforce himself.  'Giving someone a boner' now has an all new meaning...

**Comment by LordKBX** [comment]
Error corrected in last version, change the file "getify.py" or reload all the folder

**Comment by MrTazocin** [comment]
Thank you
