### ISSUE TITLE
Still only getting the announcement.

### ISSUE THREAD

**Issue by kman3107** [LordKBX/wuxiaworld_export_ebook#5]
I've checked several books and I keep getting the announcement and nothing else.
I have the downloaded the latest files.

For now the legacy application is working when I use the fix presented by moexius.
I finally tried (and wrote correct) with this application too and it seems to be working with this workaround.
`
soup = soup.find(class_="panel panel-default")
`

**Comment by arachthosproject** [comment]
hey can you tell me which version are you using?

**Comment by kman3107** [comment]
From the file "version.txt"

21/10/2018 
12:36:22,37

**Comment by LordKBX** [comment]
fixed on last version
