### ISSUE TITLE
announcement-fix

### ISSUE THREAD

**Issue by Gambizz** [LordKBX/wuxiaworld_export_ebook#6]
In the getify.py file in the clean method exchange:

for block in soups:
	if not block.has_attr('id'):
		soup = block
                break

with

for block in soups:
	classes = block.get("class", [])
	if not 'id' in classes and not 'panel-body' in classes:
		soup = block
		break

this fixes the the issue, i would do a pull request but am a bit short on time atm

**Comment by LordKBX** [comment]
fixed in last version
