### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 32: character maps to <undefined>

### ISSUE THREAD

**Issue by timabubuts** [LordKBX/wuxiaworld_export_ebook#8]
I'm dumb and somehow got it to work but my problem is that this error shows up and crashes the program.
`Traceback (most recent call last):
  File "wuxiaworld_export_ebook.pyw", line 287, in changeNovelPart2
    data_novel['books'], data_novel['alt_books'] = novel_data.import_data(data_novel['link'], novel, data_novel['limited'])
  File "C:\Users\ABUTAL\Documents\Wuxiaworld export ebook\novel_data.py", line 48, in import_data
    print(li.find('a').contents[0]);
  File "C:\Users\ABUTAL\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 32: character maps to <undefined>`
IDK what to do and youtube tutorials at this point don't cover this complexity.

Here's the link on what I look like on video
https://youtu.be/ebclncOhxmI

**Comment by LordKBX** [comment]
Could you please send me the information about your windows version ? i'm not able to reproduce this error on my PC

**Comment by timabubuts** [comment]
It seems to be doing on several novels but other novels are fine.
Emperor's domain <- has this kind of error
Edit1:
using 3.5.3 Python
Windows version: 10.0.19041 N/A Build 19041
Edit2:
Tried opening Against The Gods
this is the result

```
C:\Users\ABUTAL\wuxiaworld_export_ebook
C:\Users\ABUTAL\wuxiaworld_export_ebook
> Check script update
https://www.wuxiaworld.com/novel/against-the-gods

Prologue

Traceback (most recent call last):
  File "wuxiaworld_export_ebook.pyw", line 287, in changeNovelPart2
    data_novel['books'], data_novel['alt_books'] = novel_data.import_data(data_novel['link'], novel, data_novel['limited'])
  File "C:\Users\ABUTAL\Documents\Wuxiaworld export ebook\novel_data.py", line 48, in import_data
    print(li.find('a').contents[0]);
  File "C:\Users\ABUTAL\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2013' in position 12: character maps to <undefined>


```

**Comment by LordKBX** [comment]
I've published a new release https://github.com/LordKBX/wuxiaworld_export_ebook/releases/tag/2.0-beta04, 
You could test for verifying, for more information when testing you could add the argument noadm for more details

**Comment by timabubuts** [comment]
> I've published a new release https://github.com/LordKBX/wuxiaworld_export_ebook/releases/tag/2.0-beta04,
> You could test for verifying, for more information when testing you could add the argument noadm for more details

Works fine for showing up the books
but when exporting to e-pub same result happens (both 2 &3 version)
the novel is Emperor's Domain.

`Format Epub v3.0
Traceback (most recent call last):
  File "wuxiaworld_export_ebook.pyw", line 437, in generate
    print(status)
  File "C:\Users\ABUTAL\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 33: character maps to <undefined>
`

Edit 1: Against The Gods works fine with both showing the chapters and exporting it.

**Comment by LordKBX** [comment]
test with deleting or replace the line 437 by "print(getify.unicodeToHTMLEntities(status))" an be cautious in Python the indentation is part of the code

**Comment by timabubuts** [comment]
> test with deleting or replace the line 437 by "print(getify.unicodeToHTMLEntities(status))" an be cautious in Python the indentation is part of the code

yup, that worked pretty well.
Thank you very much ^_^
